# Site settings
title: sschuhmi's Data Science Blog
author:
  name: sschuhmi
  #email: your-email@domain.com
#description: "Data Science blog of sschuhmi"
description: ""

# Build settings
permalink: pretty
remote_theme: jekyll/minima

minima:
  skin: dark

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
