# Site settings
title: sschuhmi's Data Science Blog
author:
  name: sschuhmi
  #email: your-email@domain.com
#description: "Data Science blog of sschuhmi"
description: ""

# Build settings
remote_theme: jekyll/minima

minima:
  skin: dark

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
