# Site settings
title: sschuhmi's Data Science Blog
author:
  name: S. Schuhmann
  #email: your-email@domain.com
description: "Stephan's blog"

# Build settings
remote_theme: jekyll/minima

minima:
  skin: solarized-dark
