# Site settings
title: sschuhmi's Data Science Blog
author:
  name: S. Schuhmann
  #email: your-email@domain.com
description: "Data Science blog of sschuhmi"

# Build settings
#remote_theme: jekyll/minima
#theme: jekyll-theme-minimal
theme: jekyll/minima

minima:
  skin: dark
